package riskengine

func builtinSQLRules() []Rule {
	types := []string{"mysql", "postgresql", "d1"}
	return []Rule{
		{
			ID:          "sql-block-multi-statement",
			Code:        "SQL-011",
			Description: "Block SQL batches containing more than one statement",
			Scope:       RuleScope{DsTypes: types},
			Priority:    130,
			Action:      ActionBlock,
			Reason:      "multiple SQL statements are not allowed on agent execution paths",
			When:        RuleCondition{SQLMultiStatement: boolPtr(true)},
		},
		{
			ID:          "sql-require-approval-procedure-call",
			Code:        "SQL-012",
			Description: "Require approval for stored procedure and procedural SQL calls",
			Scope:       RuleScope{DsTypes: types},
			Priority:    115,
			Action:      ActionRequireApproval,
			Reason:      "stored procedure calls require review",
			When:        RuleCondition{Command: []string{"call", "exec", "execute", "do"}},
		},
		{
			ID:          "sql-require-approval-parser-fallback",
			Code:        "SQL-013",
			Description: "Require approval when SQL parsing fails and risk facts come from fallback parsing",
			Scope:       RuleScope{DsTypes: types},
			Priority:    80,
			Action:      ActionRequireApproval,
			Reason:      "SQL parser fallback requires review",
			When: RuleCondition{
				SQLParseFailed: boolPtr(true),
				Command:        []string{"select", "insert", "update", "delete", "replace", "alter", "create", "drop", "truncate", "grant", "revoke", "explain"},
			},
		},
		{
			ID:          "sql-allow-read",
			Code:        "SQL-001",
			Description: "Allow SELECT, SHOW, DESCRIBE, EXPLAIN",
			Scope:       RuleScope{DsTypes: types},
			Priority:    10,
			Action:      ActionAllow,
			Reason:      "read-only operation",
			When:        RuleCondition{Command: []string{"select", "show", "describe", "explain"}},
		},
		{
			ID:              "sql-allow-insert",
			Code:            "SQL-002",
			Description:     "Allow ordinary INSERT statements when explicitly enabled",
			Scope:           RuleScope{DsTypes: types},
			Priority:        60,
			Action:          ActionAllow,
			Reason:          "ordinary INSERT allowed",
			When:            RuleCondition{Command: []string{"insert"}, StatementPattern: `(?is)\binsert\b[\s\S]*\bvalues\b`},
			defaultDisabled: true,
		},
		{
			ID:          "sql-block-drop-truncate",
			Code:        "SQL-003",
			Description: "Block DROP and TRUNCATE — destructive DDL",
			Scope:       RuleScope{DsTypes: types},
			Priority:    100,
			Action:      ActionBlock,
			Reason:      "destructive DDL",
			When:        RuleCondition{Command: []string{"drop", "truncate"}},
		},
		{
			ID:          "sql-block-permission-change",
			Code:        "SQL-004",
			Description: "Block GRANT and REVOKE — permission change",
			Scope:       RuleScope{DsTypes: types},
			Priority:    100,
			Action:      ActionBlock,
			Reason:      "permission change",
			When:        RuleCondition{Command: []string{"grant", "revoke"}},
		},
		{
			ID:          "sql-block-delete-no-where",
			Code:        "SQL-005",
			Description: "Block DELETE without WHERE — affects all rows",
			Scope:       RuleScope{DsTypes: types},
			Priority:    90,
			Action:      ActionBlock,
			Reason:      "DELETE without WHERE",
			When:        RuleCondition{Command: []string{"delete"}, HasWhere: boolPtr(false)},
		},
		{
			ID:          "sql-block-update-no-where",
			Code:        "SQL-006",
			Description: "Block UPDATE without WHERE — affects all rows",
			Scope:       RuleScope{DsTypes: types},
			Priority:    90,
			Action:      ActionBlock,
			Reason:      "UPDATE without WHERE",
			When:        RuleCondition{Command: []string{"update"}, HasWhere: boolPtr(false)},
		},
		{
			ID:          "sql-warn-delete",
			Code:        "SQL-007",
			Description: "Warn on DELETE with WHERE",
			Scope:       RuleScope{DsTypes: types},
			Priority:    50,
			Action:      ActionWarn,
			Reason:      "DELETE",
			When:        RuleCondition{Command: []string{"delete"}, HasWhere: boolPtr(true)},
		},
		{
			ID:          "sql-warn-update",
			Code:        "SQL-008",
			Description: "Warn on UPDATE with WHERE",
			Scope:       RuleScope{DsTypes: types},
			Priority:    50,
			Action:      ActionWarn,
			Reason:      "UPDATE",
			When:        RuleCondition{Command: []string{"update"}, HasWhere: boolPtr(true)},
		},
		{
			ID:          "sql-warn-insert",
			Code:        "SQL-009",
			Description: "Warn on INSERT/REPLACE — write operation",
			Scope:       RuleScope{DsTypes: types},
			Priority:    40,
			Action:      ActionWarn,
			Reason:      "INSERT/REPLACE",
			When:        RuleCondition{Command: []string{"insert", "replace"}},
		},
		{
			ID:          "sql-warn-ddl",
			Code:        "SQL-010",
			Description: "Warn on ALTER/CREATE — DDL operation",
			Scope:       RuleScope{DsTypes: types},
			Priority:    40,
			Action:      ActionWarn,
			Reason:      "DDL",
			When:        RuleCondition{Command: []string{"alter", "create"}},
		},
	}
}
