package riskengine

func builtinMongoDBRules() []Rule {
	types := []string{"mongodb"}
	return []Rule{
		{
			ID:          "mongo-allow-read",
			Code:        "MDB-001",
			Description: "Allow find, aggregate, getusers, count",
			Scope:       RuleScope{DsTypes: types},
			Priority:    10,
			Action:      ActionAllow,
			Reason:      "read-only operation",
			When:        RuleCondition{Command: []string{"find", "aggregate", "getusers", "count"}},
		},
		{
			ID:              "mongo-allow-insert",
			Code:            "MDB-002",
			Description:     "Allow ordinary insert operations when explicitly enabled",
			Scope:           RuleScope{DsTypes: types},
			Priority:        60,
			Action:          ActionAllow,
			Reason:          "ordinary insert allowed",
			When:            RuleCondition{Any: []RuleCondition{{Command: []string{"insertone", "insertmany"}}, {StatementPattern: `(?i)\.insert(?:one|many)?\(`}}},
			defaultDisabled: true,
		},
		{
			ID:          "mongo-block-drop",
			Code:        "MDB-003",
			Description: "Block drop and dropDatabase — destructive operation",
			Scope:       RuleScope{DsTypes: types},
			Priority:    100,
			Action:      ActionBlock,
			Reason:      "destructive operation",
			When:        RuleCondition{Command: []string{"drop", "dropdatabase"}},
		},
		{
			ID:          "mongo-block-drop-shell-database",
			Code:        "MDB-004",
			Description: "Block dropDatabase shell command",
			Scope:       RuleScope{DsTypes: types},
			Priority:    100,
			Action:      ActionBlock,
			Reason:      "dropDatabase",
			When:        RuleCondition{StatementPattern: `(?i)dropdatabase|\.dropdatabase\(`},
		},
		{
			ID:          "mongo-block-drop-shell",
			Code:        "MDB-005",
			Description: "Block .drop() shell command",
			Scope:       RuleScope{DsTypes: types},
			Priority:    100,
			Action:      ActionBlock,
			Reason:      "drop",
			When:        RuleCondition{StatementPattern: `(?i)\.drop\(`},
		},
		{
			ID:          "mongo-block-access-control",
			Code:        "MDB-006",
			Description: "Block user and role management commands",
			Scope:       RuleScope{DsTypes: types},
			Priority:    100,
			Action:      ActionBlock,
			Reason:      "user or role management changes access control",
			When: RuleCondition{
				Any: []RuleCondition{
					{Command: []string{
						"createuser", "dropuser", "updateuser",
						"createrole", "droprole", "updaterole",
						"grantrolestouser", "revokerolesfromuser",
						"grantrolestorole", "revokerolesfromrole",
					}},
					{StatementPattern: `(?i)\b(createUser|dropUser|updateUser|createRole|dropRole|updateRole|grantRolesToUser|revokeRolesFromUser|grantRolesToRole|revokeRolesFromRole)\b`},
				},
			},
		},
		{
			ID:          "mongo-require-approval-aggregate-write",
			Code:        "MDB-007",
			Description: "Require approval for aggregation pipelines that write another collection",
			Scope:       RuleScope{DsTypes: types},
			Priority:    70,
			Action:      ActionRequireApproval,
			Reason:      "aggregation writes another collection",
			When: RuleCondition{
				Command:          []string{"aggregate"},
				StatementPattern: `(?i)\$(merge|out)`,
			},
		},
		{
			ID:          "mongo-warn-cross-collection-aggregate",
			Code:        "MDB-008",
			Description: "Warn on aggregation pipelines that join other collections",
			Scope:       RuleScope{DsTypes: types},
			Priority:    60,
			Action:      ActionWarn,
			Reason:      "aggregation spans multiple collections",
			When: RuleCondition{
				Command:          []string{"aggregate"},
				StatementPattern: `(?i)\$(lookup|unionWith)`,
			},
		},
		{
			ID:          "mongo-require-approval-collection-admin",
			Code:        "MDB-009",
			Description: "Require approval for structural collection admin commands",
			Scope:       RuleScope{DsTypes: types},
			Priority:    60,
			Action:      ActionRequireApproval,
			Reason:      "structural collection admin operation",
			When: RuleCondition{
				Any: []RuleCondition{
					{Command: []string{"renamecollection", "collmod", "dropindexes", "reindex"}},
					{StatementPattern: `(?i)\b(renameCollection|collMod|dropIndexes|reIndex)\b`},
				},
			},
		},
		{
			ID:          "mongo-warn-write",
			Code:        "MDB-010",
			Description: "Warn on write operations (delete, update, insert, index management)",
			Scope:       RuleScope{DsTypes: types},
			Priority:    50,
			Action:      ActionWarn,
			Reason:      "write operation",
			When: RuleCondition{Command: []string{
				"deletemany", "deleteone",
				"updateone", "updatemany", "replaceone",
				"findoneandupdate", "findoneandreplace", "findoneanddelete",
				"insertone", "insertmany",
				"bulkwrite",
				"createindex", "dropindex",
				"createcollection",
			}},
		},
		{
			ID:          "mongo-warn-admin-read",
			Code:        "MDB-011",
			Description: "Warn on heavy admin read commands",
			Scope:       RuleScope{DsTypes: types},
			Priority:    45,
			Action:      ActionWarn,
			Reason:      "administrative read command requires review",
			When: RuleCondition{
				Any: []RuleCondition{
					{Command: []string{"serverstatus"}},
					{StatementPattern: `(?i)\bserverStatus\b`},
				},
			},
		},
		{
			ID:          "mongo-warn-shell-write",
			Code:        "MDB-012",
			Description: "Warn on shell write operations (.delete, .remove, .update, .insert)",
			Scope:       RuleScope{DsTypes: types},
			Priority:    40,
			Action:      ActionWarn,
			Reason:      "write operation",
			When:        RuleCondition{StatementPattern: `(?i)\.(delete|remove|update|replace|insert|findoneandupdate|findoneandreplace|findoneanddelete|bulkwrite|renamecollection|collmod|dropindexes|reindex)\(`},
		},
	}
}
