package riskengine

func builtinRedisRules() []Rule {
	types := []string{"redis", "redis_cluster"}
	return []Rule{
		// === HIGH RISK: Destructive admin commands ===
		{
			ID:          "redis-block-flush",
			Code:        "RED-001",
			Description: "Block FLUSHALL/FLUSHDB — destroys all data",
			Scope:       RuleScope{DsTypes: types},
			Priority:    100,
			Action:      ActionBlock,
			Reason:      "FLUSHALL/FLUSHDB destroys all data in the database",
			When:        RuleCondition{Command: []string{"flushall", "flushdb"}},
		},
		{
			ID:          "redis-block-shutdown",
			Code:        "RED-002",
			Description: "Block SHUTDOWN — stops the server",
			Scope:       RuleScope{DsTypes: types},
			Priority:    100,
			Action:      ActionBlock,
			Reason:      "SHUTDOWN stops the Redis server",
			When:        RuleCondition{Command: []string{"shutdown"}},
		},
		{
			ID:          "redis-block-dangerous-admin",
			Code:        "RED-003",
			Description: "Block dangerous admin commands (DEBUG, CONFIG SET, CLUSTER RESET, etc.)",
			Scope:       RuleScope{DsTypes: types},
			Priority:    100,
			Action:      ActionBlock,
			Reason:      "dangerous administrative command that can destabilize the server",
			When: RuleCondition{Command: []string{
				"debug", "slaveof", "replicaof", "failover",
				"swapdb", "bgrewriteaof",
			}},
		},
		{
			ID:          "redis-block-config-set",
			Code:        "RED-004",
			Description: "Block CONFIG SET — can change server behavior",
			Scope:       RuleScope{DsTypes: types},
			Priority:    100,
			Action:      ActionBlock,
			Reason:      "CONFIG SET can change server configuration at runtime",
			When:        RuleCondition{StatementPattern: `(?i)^config\s+set\b`},
		},
		{
			ID:          "redis-block-config-resetstat",
			Code:        "RED-005",
			Description: "Block CONFIG RESETSTAT — destroys statistics",
			Scope:       RuleScope{DsTypes: types},
			Priority:    100,
			Action:      ActionBlock,
			Reason:      "CONFIG RESETSTAT clears all server statistics",
			When:        RuleCondition{StatementPattern: `(?i)^config\s+resetstat\b`},
		},
		{
			ID:          "redis-block-cluster-dangerous",
			Code:        "RED-006",
			Description: "Block dangerous CLUSTER subcommands",
			Scope:       RuleScope{DsTypes: types},
			Priority:    100,
			Action:      ActionBlock,
			Reason:      "dangerous cluster operation that can cause data loss or cluster instability",
			When:        RuleCondition{StatementPattern: `(?i)^cluster\s+(reset|flushslots|forget|failover)\b`},
		},
		{
			ID:          "redis-block-script-flush",
			Code:        "RED-007",
			Description: "Block SCRIPT FLUSH — removes all cached scripts",
			Scope:       RuleScope{DsTypes: types},
			Priority:    100,
			Action:      ActionBlock,
			Reason:      "SCRIPT FLUSH removes all cached Lua scripts",
			When:        RuleCondition{StatementPattern: `(?i)^script\s+flush\b`},
		},
		{
			ID:          "redis-block-function-dangerous",
			Code:        "RED-008",
			Description: "Block FUNCTION FLUSH/DELETE/RESTORE — changes Redis functions",
			Scope:       RuleScope{DsTypes: types},
			Priority:    100,
			Action:      ActionBlock,
			Reason:      "FUNCTION command changes server-side functions",
			When:        RuleCondition{StatementPattern: `(?i)^function\s+(flush|delete|restore)\b`},
		},
		{
			ID:          "redis-block-module-dangerous",
			Code:        "RED-009",
			Description: "Block MODULE LOAD/UNLOAD — changes loaded server modules",
			Scope:       RuleScope{DsTypes: types},
			Priority:    100,
			Action:      ActionBlock,
			Reason:      "MODULE command changes loaded server modules",
			When:        RuleCondition{StatementPattern: `(?i)^module\s+(load|loadex|unload)\b`},
		},
		{
			ID:          "redis-block-acl-dangerous",
			Code:        "RED-010",
			Description: "Block ACL DELUSER/SETUSER — permission change",
			Scope:       RuleScope{DsTypes: types},
			Priority:    100,
			Action:      ActionBlock,
			Reason:      "ACL modification can lock out users or grant unintended access",
			When:        RuleCondition{StatementPattern: `(?i)^acl\s+(deluser|setuser|load)\b`},
		},
		{
			ID:          "redis-block-client-kill",
			Code:        "RED-011",
			Description: "Block CLIENT KILL — disconnects clients",
			Scope:       RuleScope{DsTypes: types},
			Priority:    100,
			Action:      ActionBlock,
			Reason:      "CLIENT KILL disconnects active client connections",
			When:        RuleCondition{StatementPattern: `(?i)^client\s+kill\b`},
		},
		{
			ID:          "redis-block-migrate",
			Code:        "RED-012",
			Description: "Block MIGRATE — moves keys to another instance",
			Scope:       RuleScope{DsTypes: types},
			Priority:    100,
			Action:      ActionBlock,
			Reason:      "MIGRATE moves keys to another Redis instance, removing them from source",
			When:        RuleCondition{Command: []string{"migrate"}},
		},
		{
			ID:          "redis-block-memory-purge",
			Code:        "RED-013",
			Description: "Block MEMORY PURGE — forces allocator purge",
			Scope:       RuleScope{DsTypes: types},
			Priority:    100,
			Action:      ActionBlock,
			Reason:      "MEMORY PURGE changes server memory state",
			When:        RuleCondition{StatementPattern: `(?i)^memory\s+purge\b`},
		},
		{
			ID:          "redis-block-slowlog-reset",
			Code:        "RED-014",
			Description: "Block SLOWLOG RESET — clears slow log history",
			Scope:       RuleScope{DsTypes: types},
			Priority:    100,
			Action:      ActionBlock,
			Reason:      "SLOWLOG RESET clears server diagnostics history",
			When:        RuleCondition{StatementPattern: `(?i)^slowlog\s+reset\b`},
		},
		{
			ID:          "redis-block-cluster-topology-change",
			Code:        "RED-015",
			Description: "Block CLUSTER topology changes",
			Scope:       RuleScope{DsTypes: types},
			Priority:    100,
			Action:      ActionBlock,
			Reason:      "cluster topology change can destabilize the cluster",
			When:        RuleCondition{StatementPattern: `(?i)^cluster\s+(addslots|addslotsrange|delslots|delslotsrange|meet|replicate|setslot)\b`},
		},

		// === MEDIUM RISK: Write operations ===
		{
			ID:          "redis-warn-write",
			Code:        "RED-016",
			Description: "Warn on write commands (SET, DEL, HSET, etc.)",
			Scope:       RuleScope{DsTypes: types},
			Priority:    50,
			Action:      ActionWarn,
			Reason:      "write operation",
			When: RuleCondition{Command: []string{
				"del", "unlink",
				"set", "mset", "msetnx", "setnx", "setex", "psetex", "append", "setrange", "getset", "getdel",
				"incr", "decr", "incrby", "decrby", "incrbyfloat",
				"hset", "hmset", "hsetnx", "hdel", "hincrby", "hincrbyfloat",
				"lpush", "rpush", "lpushx", "rpushx", "lpop", "rpop", "lset", "linsert", "lrem", "ltrim", "rpoplpush", "lmove", "lmpop",
				"sadd", "srem", "spop", "smove", "sdiffstore", "sinterstore", "sunionstore",
				"zadd", "zrem", "zincrby", "zpopmin", "zpopmax", "zrangestore", "zdiffstore", "zinterstore", "zunionstore", "zmpop",
				"xadd", "xdel", "xtrim", "xack",
				"expire", "pexpire", "expireat", "pexpireat", "persist",
				"rename", "renamenx",
				"copy", "move",
				"pfadd", "pfmerge",
				"geoadd", "georadius", "georadiusbymember",
				"bitop", "bitfield", "setbit",
			}},
		},

		// === MEDIUM RISK: Scan operations (performance risk) ===
		{
			ID:          "redis-warn-scan",
			Code:        "RED-017",
			Description: "Warn on KEYS/SCAN operations — O(N) performance impact",
			Scope:       RuleScope{DsTypes: types},
			Priority:    50,
			Action:      ActionWarn,
			Reason:      "O(N) scan operation; may block Redis on large datasets",
			When: RuleCondition{Command: []string{
				"keys", "scan", "sscan", "hscan", "zscan",
				"hgetall", "smembers",
				"zrange", "zrevrange", "zrangebyscore", "zrevrangebyscore", "zrangebylex",
				"lrange",
				"xrange", "xrevrange", "xread",
				"sort",
			}},
		},
		{
			ID:          "redis-warn-bounded-read",
			Code:        "RED-018",
			Description: "Warn on read commands that can still return large payloads or block",
			Scope:       RuleScope{DsTypes: types},
			Priority:    45,
			Action:      ActionWarn,
			Reason:      "read operation can return a large payload or change session behavior",
			When: RuleCondition{Command: []string{
				"hkeys", "hvals", "hrandfield",
				"srandmember",
				"zrandmember",
				"xinfo", "xpending",
				"geosearch",
				"bitcount", "bitpos",
				"object",
				"subscribe", "psubscribe", "ssubscribe",
				"wait", "waitaof", "select",
			}},
		},

		// === MEDIUM RISK: Lua scripting ===
		{
			ID:          "redis-require-approval-lua-write",
			Code:        "RED-022",
			Description: "Require approval for Lua scripts with detected write intent",
			Scope:       RuleScope{DsTypes: types},
			Priority:    70,
			Action:      ActionRequireApproval,
			Reason:      "Lua script invokes a Redis write command",
			When:        RuleCondition{OperationClass: []string{operationClassScript, operationClassWrite}},
		},
		{
			ID:          "redis-warn-eval",
			Code:        "RED-019",
			Description: "Warn on EVAL/EVALSHA — arbitrary Lua execution",
			Scope:       RuleScope{DsTypes: types},
			Priority:    50,
			Action:      ActionWarn,
			Reason:      "Lua script execution; can perform arbitrary operations",
			When:        RuleCondition{Command: []string{"eval", "evalsha", "eval_ro", "evalro", "evalsha_ro", "fcall", "fcall_ro"}},
		},
		{
			ID:          "redis-warn-admin-families",
			Code:        "RED-020",
			Description: "Warn on CONFIG/CLIENT/CLUSTER command families unless a higher-priority block rule matches",
			Scope:       RuleScope{DsTypes: types},
			Priority:    50,
			Action:      ActionWarn,
			Reason:      "administrative command family requires review",
			When:        RuleCondition{Command: []string{"config", "client", "cluster", "acl", "function", "module"}},
		},

		// === LOW RISK: Read-only operations ===
		{
			ID:          "redis-allow-read",
			Code:        "RED-021",
			Description: "Allow read-only O(1) commands",
			Scope:       RuleScope{DsTypes: types},
			Priority:    10,
			Action:      ActionAllow,
			Reason:      "read-only operation",
			When: RuleCondition{Command: []string{
				"get", "mget", "getrange", "strlen",
				"type", "ttl", "pttl", "exists", "dump", "debug",
				"hget", "hmget", "hexists", "hlen",
				"lindex", "llen", "lpos",
				"scard", "sismember", "smismember",
				"zcard", "zscore", "zmscore", "zrank", "zrevrank", "zlexcount", "zcount",
				"xlen",
				"pfcount",
				"geopos", "geodist", "geohash",
				"getbit",
				"dbsize", "randomkey",
				"info", "ping", "echo", "time", "lastsave",
				"slowlog", "memory",
				"pubsub",
			}},
		},
	}
}
